---
name         : 'MWLR Standards Action'
author       : 'Maanaki Whenua Landcare Research'
description  : "An action to check the respitory meets Maanaki Whenua Landcare Research's standards"
runs         :
  using      : 'docker'
  image      : 'docker://debian:stretch-slim'
  entrypoint : 'entrypoint.bash'
branding     :
  icon       : 'award'
  color      : 'green'